// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Initializes a Supabase client instance for interacting with the specified database.
 *
 * @remarks
 * The client is configured to use `localStorage` for authentication storage,
 * persist user sessions across browser reloads, and automatically refresh tokens.
 *
 * @typeParam Database - The database schema type for type-safe queries.
 *
 * @see {@link https://supabase.com/docs/reference/javascript/createclient | Supabase createClient documentation}
 *
 * @example
 * ```typescript
 * const { data, error } = await supabase.from('users').select('*');
 * ```
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
